# Generated by Django 3.2.4 on 2021-06-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Configuration', '0001_initial'),
        ('Location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuration.business')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
