# Generated by Django 3.2.4 on 2021-06-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='uploads/Product')),
                ('price', models.PositiveIntegerField()),
                ('discount_percent', models.PositiveIntegerField()),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
